name=input("Enter Your Name:")
print("welcome",name)
val1=input("Enter value 1:")
val2=(input("enter value 2:"))
print("adding val1 character to val2:",val1+val2)
val1=int(input("Enter value 1:"))
val2=int((input("enter value 2:")))
print("adding val1 character to val2:",val1+val2)
val1=int(input("Enter value 1:"))
val2=float((input("enter value 2:")))
print("adding val1 character to val2:",val1+val2)